version: "3"

services:
  next-app-prod:
    image: next-app-prod
    container_name: next-app-prod
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - "4422:3000"
    networks:
      - share-network

  nest-service-dev:
    image: nest-service-prod
    container_name: nest-service-prod
    build:
      context: ./nest-service
      dockerfile: nest.prod.Dockerfile
    restart: always
    ports:
      - "5000:4000"
    networks:
      - share-network
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  share-network:
#    external: true
