version: "3"

services:
  next-app-dev:
    image: next-app-dev
    container_name: next-app-dev
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - "4000:3000"
    depends_on:
      - nest-service-dev
    networks:
      - share-network

  nest-service-dev:
    image: nest-service-dev
    container_name: nest-service-dev
    build:
      context: ./nest-service
      dockerfile: nest.dev.Dockerfile
      args:
        MONGO_DATABASE: ${MONGO_DATABASE}
        MONGO_USERNAME: ${MONGO_USERNAME}
        MONGO_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./nest-service/src:/app/src
    restart: always
    ports:
      - "5000:4000"
    depends_on:
      - mongo
    networks:
      - share-network

  mongo:
    image: mongo:latest
    container_name: mongo
#    volumes:
#      - /data/mongodb_data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - share-network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  share-network:
    external: true
volumes:
  myVolumes:
