name: Build and Deploy
on: # 监听 master 分支上的 push 事件
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: CentOS 8.2 # 构建环境使用
    steps:
      - uses: actions/checkout@v1
      # - name: Install Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "12.16.2"
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.TENCENT_TEST }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: bbs_next # 这是要复制到阿里云静态服务器的文件夹名称
          REMOTE_HOST: "43.142.47.50" # 你的阿里云公网地址
          REMOTE_USER: root # 阿里云登录后默认为 root 用户，并且所在文件夹为 root
          TARGET: /root/bbs_dist # 打包后的 dist 文件夹将放在 /root/node-server
