name: Docker Next CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }}
          docker compose -f docker-compose.prod.yml build
          docker tag next-app-prod ${{ secrets.DOCKER_USERNAME }}/next-app-prod
          docker tag nest-service-prod ${{ secrets.DOCKER_USERNAME }}/nest-service-prod
          echo "docker image build over"
          docker push ${{ secrets.DOCKER_USERNAME }}/next-app-prod
          docker push ${{ secrets.DOCKER_USERNAME }}/nest-service-prod
          echo "docker image pull over"

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TENCENT_HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          #password: ${{ secrets.TENCENT_HOST_P }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/next-app-prod
            docker pull ${{ secrets.DOCKER_USERNAME }}/nest-service-prod
            docker pull mongo:latest
            echo "docker image pull over"
            docker stop next-app-prod
            docker rm -f next-app-prod
            docker rm -f nest-service-prod
            docker rm -f mongo
            docker run --name mongo -d -p 27017:27017 -e MONGO_INITDB_DATABASE=${{ secrets.MONGO_DATABASE }} -e MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_USERNAME }} -e MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_PASSWORD }} --network share-network mongo:latest
            docker run --name next-app-prod -d -p 4422:3000 ${{ secrets.DOCKER_USERNAME }}/next-app-prod
            docker run --name nest-service-prod -d -p 5000:4000 --network share-network ${{ secrets.DOCKER_USERNAME }}/nest-service-prod
            docker image prune -f
            docker container prune -f
